my_conf = {
    "save_path": "/home/ubuntu/rentianxiang/NSM/trained-tese",
    "load_path": "/home/ubuntu/rentianxiang/NSM/trained-test",
    "CUDA_VISIBLE_DEVICES": "0,1,2,3",
    "CUDA_USE": [0,1,2,3],
    "data": "/home/ubuntu/rentianxiang/NSM",
    "model": {
        'model_name': 'NSM',
        'epoch': 150,
        'batch_size': 1200,
        'segmentation': [0, 419, 575, 2609, 4657, 5307],
        'encoder_nums': 4,
        'encoder_dims': [[419, 512, 512],
                         [156, 128, 128],
                         [2034, 512, 512],
                         [2048, 512, 512]],
        'encoder_activations': [['elu', 'elu'],
                                ['elu', 'elu'],
                                ['elu', 'elu'],
                                ['elu', 'elu']],
        'encoder_dropout': 0.3,
        'expert_components': [1, 10],
        'expert_dims': [[650, 512, 512, 10],
                        [1664, 512, 512, 618]],
        'expert_activations': [['elu', 'elu', 'softmax'],
                               ['elu', 'elu', None]],
        'expert_dropout': 0.3,
        'lr': 0.001,
    },
}
